theme: jekyll-theme-Minima
title:  Developing statistical downscaling to improve water quality understanding and management in the Ramganga sub-basin
descripttion:  Developing statistical downscaling to improve water quality understanding and management in the Ramganga sub-basin
logo: "images/uog.png"
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
