theme: jekyll-theme-cayman
title: EPSRC supported Research Project on water quality of Ramganga
descripttion:  Developing statistical downscaling to improve water quality understanding and management in the Ramganga sub-basin
logo: "images/uog.png"
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
