theme: jekyll-theme-cayman
title:  Ramganga
description:  Developing statistical downscaling to improve water quality understanding and management in the Ramganga sub-basin
tagline:  Developing statistical downscaling to improve water quality understanding and management in the Ramganga sub-basin
logo: "assets/logo/logo3.png"
defaults:
  # _docs
  - scope:
      path: "images/"
      type: docs
    values:
      sidebar:
        nav: "docs"
github:
  is_project_page: false