theme: jekyll-theme-cayman
title:  Covid-19 research group
description:  Use of Machine Learning and Artificial Intelligence to predict SARS-CoV-2 infection from Full Blood Counts in a population
tagline:  Use of Machine Learning and Artificial Intelligence to predict SARS-CoV-2 infection from Full Blood Counts in a population
logo: "assets/logo/blood.jpeg"
defaults:
  # _docs
  - scope:
      path: "images/"
      type: docs
    values:
      sidebar:
        nav: "docs"
github:
  is_project_page: false
