theme: jekyll-theme-cayman
title:  Clinical Predictive Modelling Research Group 
description:  Using  Machine Learning and Artificial Intelligence to solve SARS-CoV-2 Pandemic
tagline:  Use of Machine Learning and Artificial Intelligence to predict SARS-CoV-2 infection from Full Blood Counts in a population
logo: "assets/logo/blood.jpeg"
defaults:
  # _docs
  - scope:
      path: "images/"
      type: docs
    values:
      sidebar:
        nav: "docs"
github:
  is_project_page: false
